In [1]:
import numpy as np

### Задание 1

In [5]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Задание 2

In [10]:
n=int(input())

matrix = np.diag(np.arange(n,0,-1))
print(matrix)

10
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]


In [11]:
sum_diag = 0

for i, element in enumerate(matrix):
    sum_diag += element[i]
print(sum_diag)

55


### Задание 3
4x + 2y + z = 4 
x + 3y = 12
5y + 4z = -3

In [71]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

In [72]:
b = np.array([4, 12, -3])

In [73]:
from numpy import linalg

In [74]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

In [76]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [77]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [86]:
def cosine(users_stats, next_user_stats):
    All_Length = np.sqrt((users_stats * users_stats).sum())
    next_Length = np.sqrt((next_user_stats * next_user_stats).sum())
    
    return np.dot(users_stats, next_user_stats) / ( All_Length * next_Length )

In [87]:
cosine(users_stats, next_user_stats)

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

In [88]:
all_users = np.array([cosine(row, next_user_stats) for row in users_stats])

In [89]:
similar_user = np.argmax(muls)
similar_user

7